# Generated by Django 4.0.3 on 2024-08-05 12:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=50)),
                ('health_requirements', models.TextField()),
                ('food_requirements', models.TextField()),
                ('periodic_medications', models.TextField()),
                ('observations', models.TextField()),
                ('exp', models.IntegerField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='child_images/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Childs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('Profesor', 'Profesor'), ('Progenitor', 'Progenitor')], default='Admin', max_length=20)),
            ],
            options={
                'verbose_name': 'UserApp',
                'verbose_name_plural': 'UsersApp',
                'managed': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Resumen')),
                ('type', models.CharField(choices=[('Salud', 'Salud'), ('Logros', 'Logros')], max_length=50)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'ReportChild',
                'verbose_name_plural': 'ReportChilds',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=50, null=True, verbose_name='NIP')),
                ('date_birth', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Teléfono')),
                ('school_level', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Técnica y Profesional', 'Técnica y Profesional'), ('Medio Superior', 'Medio Superior'), ('Superior', 'Superior')], max_length=50, null=True, verbose_name='Nivel escolar')),
                ('cv', models.FileField(null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='child_images/')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Apellidos')),
                ('nip', models.CharField(max_length=50, null=True, verbose_name='NIP')),
                ('date_birth', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Teléfono')),
                ('school_level', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Técnica y Profesional', 'Técnica y Profesional'), ('Medio Superior', 'Medio Superior'), ('Superior', 'Superior')], max_length=50, null=True, verbose_name='Nivel escolar')),
                ('work_center', models.CharField(max_length=1000, null=True, verbose_name='Centro de trabajo')),
                ('position', models.CharField(max_length=1000, null=True, verbose_name='Cargo')),
                ('illnesses', models.CharField(max_length=1000, null=True, verbose_name='Enfermedades que padece')),
                ('alcoholism', models.BooleanField(null=True, verbose_name='Alcoholismo')),
                ('smoking', models.BooleanField(null=True, verbose_name='Tabaquismo')),
                ('mother', models.BooleanField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Childs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('ic', models.CharField(max_length=50, null=True)),
                ('relationship', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.child')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Familys',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('age_range', models.CharField(choices=[('1 a 3 años', '1 a 3 años'), ('3 a 5 años', '3 a 5 años'), ('más de 5 años', 'más de 5 años')], max_length=50)),
                ('cover', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('childs', models.ManyToManyField(null=True, to='core.child')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ClassGroup',
                'verbose_name_plural': 'ClassGroups',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50)),
                ('amount', models.FloatField()),
                ('paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('publish', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
