# Generated by Django 4.0.3 on 2024-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('visit_count', models.IntegerField(default=0)),
                ('last_visited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PageVisit',
                'verbose_name_plural': 'PageVisits',
                'managed': True,
            },
        ),
    ]
