# Generated by Django 4.0.3 on 2024-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='url',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
