# Generated by Django 5.0.2 on 2024-08-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pagevisit_url_pagevisit_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parent'),
        ),
    ]
