# Generated by Django 5.0.2 on 2024-08-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_parent_child_child_father_child_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='nip',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
