# Generated by Django 5.0.2 on 2024-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userapp_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='mother',
            field=models.BooleanField(default=True),
        ),
    ]
