# Generated by Django 5.0.2 on 2024-08-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userapp_mother'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'managed': True, 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='mother',
            new_name='is_mother',
        ),
        migrations.AlterField(
            model_name='child',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='core.parent'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='core.parent'),
        ),
    ]
