# Generated by Django 5.0.2 on 2024-08-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_parent_options_rename_mother_parent_is_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='publish',
            field=models.DateField(),
        ),
    ]
