# Generated by Django 5.0.2 on 2024-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_alert_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Profesor', 'Profesor'), ('Progenitor', 'Progenitor'), ('Supervisor', 'Supervisor')], default='Admin', max_length=20),
        ),
    ]
