# Generated by Django 5.0.2 on 2024-08-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userapp_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
