# Generated by Django 5.0.2 on 2024-08-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userapp_terms_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], max_length=50, null=True),
        ),
    ]
