# Generated by Django 5.0.2 on 2024-08-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_family_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='child',
            name='date_down',
            field=models.DateField(null=True),
        ),
    ]
