# Generated by Django 5.0.2 on 2024-08-30 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bill_active_child_date_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child'),
        ),
    ]
