# Generated by Django 5.0.2 on 2024-09-02 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_bill_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='month',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=50, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child', verbose_name='Niño/a'),
        ),
        migrations.AlterField(
            model_name='child',
            name='nip',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='nip',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nip',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='nip',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('paid', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('ic', 'relationship')},
        ),
    ]
